name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: website-2023/package-lock.json
      - name: Install Dependencies
        working-directory: website-2023
        run: npm install
      - name: Set Git Identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/
      - name: Publish to GitHub Pages
        working-directory: website-2023
        run: npm run deploy
